### ISSUE TITLE
Inmunity should be an input parameter

### ISSUE THREAD

**Issue by dalonsoa** [bnc19/ReCoDE_IDMS#3]
The immunity value (in this case taken from a paper) should be a separate input parameter, making `N` and actual derived quantity.

https://github.com/bnc19/ReCoDE_IDMS/blob/cd46453dd51d72fc2398f017057520105d60bf56/Model%201/scripts/simulate_data_run_model.R#L50

So, I would would suggest:

```R
immunity = 0.562
R = round(N * immunity)
```

**Comment by bnc19** [comment]
Have updated.
