### ISSUE TITLE
Separate function that simulates the initial data

### ISSUE THREAD

**Issue by dalonsoa** [bnc19/ReCoDE_IDMS#4]
The function that simulates an initial data should be in a separate file, too. It should:

- Accept all the relevant inputs (eg. N, gamma, etc.)
- Create the initial state object as well as any other derived quantities for the model to run.
- Solve the ODE
- Return the dataframe with the simulated data

https://github.com/bnc19/ReCoDE_IDMS/blob/cd46453dd51d72fc2398f017057520105d60bf56/Model%201/scripts/simulate_data_run_model.R#L56

**Comment by bnc19** [comment]
Done, this is now the file: [simulate_model1_data.Rmd].
